### PR TITLE
Psych engine 0.7.0 stuff and more

### PR DESCRIPTION
**Pull request by EdwhakKB**
I just fixed the 0.7 stuff and added some visual good stuff such as (eventModifier image instead of noteSkin for psych), added TweenManagers for stuff and same for times, also a lua documentation with added Modifiers lol
have fun i guess

### CODE REVIEW

**Comment by roma-perec-bp** [comment]
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:86: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:88: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:89: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:90: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:91: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:92: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:93: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:94: characters 23-31 : Class<psychlua.FunkinLua> has no field instance
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : flixel.util.FlxAxes should be Float
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : ... For optional function argument 'ScrollX'

did u even tested ur thing?

**Comment by roma-perec-bp** [comment]
and not only that, there was still another organized folder stuff issues (conductor and clientprefs mostly)

**Comment by EdwhakKB** [comment]
> C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:86: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:88: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:89: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:90: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:91: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:92: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:93: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:94: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : flixel.util.FlxAxes should be Float C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : ... For optional function argument 'ScrollX'
> 
> did u even tested ur thing?

sorry i forgot the funkin lua thing

the fix its just add this code inside funkin lua 
`public static var instance:FunkinLua = null;`

other stuff inside modchart thing its something you added
and can you give the bugs for the Conductor and ClientPrefs stuff please?

**Review by Sword352 — APPROVED** [review]
Actually fire PR, I just don't really know why we are making new timers for each functions of the TimerManager class but otherwise looks cool

**Comment by roma-perec-bp** [comment]
изображение_2023-07-27_123944718

uhh u gotta soon do fix for 0,7h

**Comment by roma-perec-bp** [comment]
> > C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:86: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:88: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:89: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:90: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:91: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:92: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:93: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartFuncs.hx:94: characters 23-31 : Class<psychlua.FunkinLua> has no field instance C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : flixel.util.FlxAxes should be Float C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:417: characters 113-122 : ... For optional function argument 'ScrollX'
> > did u even tested ur thing?
> 
> sorry i forgot the funkin lua thing
> 
> the fix its just add this code inside funkin lua `public static var instance:FunkinLua = null;`
> 
> other stuff inside modchart thing its something you added and can you give the bugs for the Conductor and ClientPrefs stuff please?

C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:104: characters 18-23 : Type not found : Paths
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:191: characters 16-25 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:347: characters 3-12 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:348: characters 3-12 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:352: characters 60-65 : Type not found : Paths
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:390: characters 29-40 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1006: characters 9-18 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1013: characters 50-55 : Type not found : Paths
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1014: characters 53-58 : Type not found : Paths
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1027: characters 44-49 : Type not found : Paths
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1033: characters 13-22 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1107: characters 41-50 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1117: characters 72-81 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1165: characters 21-32 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1194: characters 53-64 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1195: characters 36-47 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:1207: characters 20-31 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:2105: characters 4-13 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:526: characters 9-18 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:529: characters 34-43 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:536: characters 49-58 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:561: characters 17-28 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:573: characters 13-24 : Type not found : ClientPrefs
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:612: characters 50-59 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:631: characters 31-40 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:640: characters 31-40 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:678: characters 75-84 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:693: characters 17-26 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:710: characters 17-26 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:770: characters 29-38 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:772: characters 30-39 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:823: characters 46-55 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:828: characters 33-42 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:842: characters 58-67 : Type not found : Conductor
C:/HaxeToolkit/haxe/lib/fnf-modcharting-tools/git/source/modcharting/ModchartEditorState.hx:2274: characters 60-65 : Type not found : Paths

smth like this and not only in editorstate

**Comment by EdwhakKB** [comment]
weird, you are the only one that get that bug hmmm, i think i should see what breaks, for now continue with 0.6.3 while zoro or i fix that

**Comment by roma-perec-bp** [comment]
0.7.1 is out btw

**Comment by roma-perec-bp** [comment]
Thats why

**Comment by EdwhakKB** [comment]
OOOOH, okay i'll see whats wrong now then

**Comment by roma-perec-bp** [comment]
Basically i had issues with hscript, in modchart func there is hscript.variable.set stuff and it saying null reference

**Comment by EdwhakKB** [comment]
oh well, idk a lot of Hscript but i know someone who knows, we will fix that if zoro don't fix it for now

**Comment by roma-perec-bp** [comment]
Imagine if he will merge it lmao

**Comment by roma-perec-bp** [comment]
image

yo dude just saying
 only this makes game crash, i tested

**Comment by roma-perec-bp** [comment]
wait i just saw that i cant see sustains

**Comment by EdwhakKB** [comment]
sustains breaks?
hmmm weird

**Comment by roma-perec-bp** [comment]
They became invisible, idk if its only me since i didnt touched sustains really deep but yeah, sustains moment

**Comment by roma-perec-bp** [comment]
In editor i cant see em too

**Comment by EdwhakKB** [comment]
weird, it don't happen to me hmmm

**Comment by roma-perec-bp** [comment]
Hmm well then i think i fucked up smth and its on note.hx thank god not playstate

**Comment by roma-perec-bp** [comment]
wait, no, my note.hx is almost same but it still makes sustains notes be invisible

**Comment by EdwhakKB** [comment]
is there any other bug that you get?

**Comment by roma-perec-bp** [comment]
Nope

**Comment by EdwhakKB** [comment]
okay, if there is any other bug then tell me on my discord instead lmao
"@edwhak_kb"

**Comment by roma-perec-bp** [comment]
Alr

**Review by ender69flock — CHANGES_REQUESTED** [review]
Good job

**Review by ender69flock — APPROVED** [review]
gud

**Pull request closed without merging**
